name: woomul
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #백앤드 개발 패키지
  collection: ^1.16.0
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  provider: ^6.0.4
  http: ^0.13.5
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.5

  #splash 화면 만들기
  flutter_native_splash: ^2.2.16

  percent_indicator: ^4.0.1
  google_fonts: ^3.0.1

  #FCM
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0

  flutter_rounded_date_picker: 3.0.2

  hive: ^2.2.2
  hive_flutter: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/chara/
    - assets/images/board/